package todev

import (
	"context"
	"fmt"
	"time"
	"unicode/utf8"
)

// Repo constants.
const (
	MaxRepoNameLen = 100
)

// Repo represents a github project on which the the owner of the repo
// adds tasks for the team (contributors).
type Repo struct {
	ID int `json:"id"`

	// Owner of the repo.
	UserID int   `json:"userID"`
	User   *User `json:"user"`

	// Human-readable name of repo.
	Name string `json:"name"`

	// Code used to share the repo with other users.
	InviteCode string `json:"inviteCode,omitempty"`

	// List of the tasks attached to the repo.
	Tasks []Task `json:"tasks"`

	// Timestamps for repo creation and last update.
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`

	// List of associated members and their contributing tasks.
	Memberships []*RepoMembership `json:"memberships,omitempty"`
}

// MembershipByUserID returns the membership attached to the repo for the given user ID.
func (r Repo) MembershipByUserID(ctx context.Context, userID int) *RepoMembership {
	for _, m := range r.Memberships {
		if m.UserID == userID {
			return m
		}
	}
	return nil
}

// TasksByRepoMembershipID returns the tasks attached to membership by the given membership ID.
func (r Repo) TasksByRepoMembershipID(ctx context.Context, membershipID int) ([]*Task, error) {
	for _, m := range r.Memberships {
		if m.ID == membershipID {
			tasks := make([]*Task, len(m.Tasks))
			for i := 0; i < len(tasks); i++ {
				tasks[i] = m.Tasks[i]
			}
			return tasks, nil
		}
	}
	return nil, Errorf(ENOTFOUND, "No membership for the given id: %d", membershipID)
}

// Validate retruns an error if a repo has invalid fields.
func (r Repo) Validate() error {
	if r.Name == "" {
		return Errorf(EINVALID, "Repo name required.")
	} else if utf8.RuneCountInString(r.Name) > MaxRepoNameLen {
		return Errorf(EINVALID, "Repo name too long.")
	} else if r.UserID == 0 {
		return Errorf(EINVALID, "Repo creator required.")
	}
	return nil
}

// CanEditRepo returns true if the current user can edit the repo.
func CanEditRepo(ctx context.Context, repo *Repo) bool {
	return repo.UserID == UserIDFromContext(ctx)
}

// RepoService represents a service for managing repos.
type RepoService interface {
	// Retrieves a single repo by ID along with associated memberships.
	FindRepoByID(ctx context.Context, id int) (*Repo, error)

	// Retrieves a list of repos based on a filter.
	FindRepos(ctx context.Context, filter RepoFilter) ([]*Repo, int, error)

	// Creates a new repo and assigns the current user as the owner.
	CreateRepo(ctx context.Context, repo Repo) error

	// Updates an existing repo by ID. Only the repo owner can update a repo.
	UpdateRepo(ctx context.Context, id int, upd RepoUpdate) (*Repo, error)

	// Permanently deletes a repo by ID. Only the repo owner can delete a repo.
	DeleteRepo(ctx context.Context, id int) error

	// Sets a task for the given user's membership in a repo.
	SetRepoMembershipTask(ctx context.Context, repoID int, task Task) error

	// TasksLeftReport returns a report of all the tasks due in this repo.
	TasksLeftReport(ctx context.Context, start, end time.Time, interval time.Duration) (*RepoTasksReport, error)
}

// RepoFilter represents a filter used by FilterRepo().
type RepoFilter struct {
	// Filtering fields.
	ID         *int    `json:"id"`
	InviteCode *string `json:"inviteCode"`

	// Restrict to subset of range.
	Offset int `json:"offset"`
	Limit  int `json:"limit"`
}

// RepoUpdate represents a set of fields to update on a repo.
type RepoUpdate struct {
	Name *string `json:"name"`
}

// RepoTasksReport represents a report generated by TasksLeftReport().
type RepoTasksReport struct {
	Records []*RepoTasksRecord
}

// RepoTasksRecord represents all uncompleted tasks.
type RepoTasksRecord struct {
	Tasks     []Task    `json:"tasks"`
	Timestamp time.Time `json:"timestamp"`
}

// GoString prints a more easily readable report representation for debugging.
func (r *RepoTasksRecord) GoString() string {
	return fmt.Sprintf("&todev.RepoTasksRecord(\n    Tasks:%v,\n    Timestamp:%q)", r.Tasks, r.Timestamp.Format(time.RFC3339))
}
