CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(18) NOT NULL,
	email VARCHAR(255) UNIQUE,
	api_key TEXT NOT NULL UNIQUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
